[build-system]
requires = ["setuptools>=68", "wheel", "Cython>=0.29.36", "numpy>=2.0"]
build-backend = "setuptools.build_meta"

[project]
name = "optimizer"
version = "0.1.0"
requires-python = ">=3.11"

[tool.setuptools.package-dir]
"" = "src"